openapi: 3.1.0
jsonSchemaDialect: https://spec.openapis.org/oas/3.1/dialect/base
info:
  title: Dwolla API
  description: Dwolla API Documentation
  contact:
    name: Dwolla Developer Relations Team
    url: 'https://developers.dwolla.com'
    email: api@dwolla.com
  version: '2.0'
  termsOfService: 'https://www.dwolla.com/legal/tos/'
  license:
    name: MIT
    url: 'https://github.com/Dwolla/dwolla-openapi/blob/master/LICENSE'
servers:
  - url: 'https://api.dwolla.com'
    description: Production server
  - url: 'https://api-sandbox.dwolla.com'
    description: Sandbox server
paths:
  /token:
    $ref: './resources/authorization.yml'
  /:
    $ref: './resources/root.yml'
  /accounts/{id}:
    $ref: './resources/accounts/retrieveAccount.yml'
  /funding-sources:
    $ref: './resources/accounts/createAccountFundingSource.yml'
  /accounts/{id}/funding-sources:
    $ref: './resources/accounts/listAccountFundingSources.yml'
  /accounts/{id}/transfers:
    $ref: './resources/accounts/listAndSearchAccountTransfers.yml'
  /accounts/{id}/mass-payments:
    $ref: './resources/accounts/listAccountMassPayments.yml'
  /customers:
    $ref: './resources/customers/createListCustomers.yml'
  /customers/{id}:
    $ref: './resources/customers/retrieveUpdateCustomer.yml'
  /business-classifications:
    $ref: './resources/customers/listBusinessClassifications.yml'
  /business-classifications/{id}:
    $ref: './resources/customers/retrieveBusinessClassification.yml'
  /customers/{id}/beneficial-owners:
    $ref: './resources/beneficial-owners/createListBeneficialOwners.yml'
  /beneficial-owners/{id}:
    $ref: './resources/beneficial-owners/retrieveUpdateRemoveBeneficialOwner.yml'
  /customers/{id}/beneficial-ownership:
    $ref: './resources/beneficial-owners/retrieveCertifyBeneficialOwnership.yml'
  /customers/{id}/documents:
    $ref: './resources/documents/createListCustomerDocuments.yml'
  /beneficial-owners/{id}/documents:
    $ref: './resources/documents/createListBeneficialOwnerDocuments.yml'
  /documents/{id}:
    $ref: './resources/documents/retrieveDocument.yml'
  /customers/{id}/kba:
    $ref: './resources/kba/initiateKba.yml'
  /kba/{id}:
    $ref: './resources/kba/verifyRetrieveKba.yml'
  /customers/{id}/funding-sources:
    $ref: './resources/funding-sources/createListCustomerFundingSources.yml'
  /funding-sources/{id}:
    $ref: './resources/funding-sources/retrieveUpdateRemoveFundingSource.yml'
  /funding-sources/{id}/micro-deposits:
    $ref: './resources/funding-sources/retrieveInitiateVerifyMicroDeposit.yml'
  /funding-sources/{id}/balance:
    $ref: './resources/funding-sources/retrieveFundingSourceBalance.yml'
  /funding-sources/{id}/ach-routing:
    $ref: './resources/funding-sources/retrieveVansAccountRoutingNumber.yml'
  /on-demand-authorizations:
    $ref: './resources/funding-sources/createOnDemandTransferAuthorization.yml'
  /transfers:
    $ref: './resources/transfers/initiateTransfer.yml'
  /transfers/{id}:
    $ref: './resources/transfers/retrieveCancelTransfer.yml'
  /customers/{id}/transfers:
    $ref: './resources/transfers/listAndSearchCustomerTransfers.yml'
  /transfers/{id}/fees:
    $ref: './resources/transfers/listFeesForTransfer.yml'
  /transfers/{id}/failure:
    $ref: './resources/transfers/retrieveTransferFailureReason.yml'
  /mass-payments:
    $ref: './resources/mass-payments/initiateMassPayment.yml'
  /mass-payments/{id}:
    $ref: './resources/mass-payments/retrieveUpdateMassPayment.yml'
  /mass-payments/{id}/items:
    $ref: './resources/mass-payments/listMassPaymentItems.yml'
  /mass-payment-items/{itemId}:
    $ref: './resources/mass-payments/retrieveMassPaymentItem.yml'
  /customers/{id}/mass-payments:
    $ref: './resources/mass-payments/listMassPaymentsForCustomer.yml'
  /labels/{id}:
    $ref: './resources/labels/retrieveRemoveLabel.yml'
  /customers/{id}/labels:
    $ref: './resources/labels/createListCustomerLabels.yml'
  /labels/{id}/ledger-entries:
    $ref: './resources/labels/createListLabelLedgerEntries.yml'
  /ledger-entries/{ledgerEntryId}:
    $ref: './resources/labels/retrieveLabelLedgerEntry.yml'
  /label-reallocations:
    $ref: './resources/labels/createLabelReallocation.yml'
  /label-reallocations/{reallocationId}:
    $ref: './resources/labels/retrieveLabelReallocation.yml'
  /events:
    $ref: './resources/events/listEvents.yml'
  /events/{id}:
    $ref: './resources/events/retrieveEvent.yml'
  /webhook-subscriptions:
    $ref: './resources/webhook-subscriptions/createListWebhookSubscriptions.yml'
  /webhook-subscriptions/{id}:
    $ref: './resources/webhook-subscriptions/retrieveUpdateDeleteWebhookSubscription.yml'
  /webhook-subscriptions/{id}/webhooks:
    $ref: './resources/webhook-subscriptions/listWebhooksForWebhookSubscription.yml'
  /webhooks/{id}:
    $ref: './resources/webhooks/retrieveWebhook.yml'
  /webhooks/{id}/retries:
    $ref: './resources/webhooks/listRetriesAndRetryWebhook.yml'
  /exchange-partners:
    $ref: './resources/exchanges/listExchangePartners.yml'
  /exchange-partners/{id}:
    $ref: './resources/exchanges/retrieveExchangePartner.yml'
  /exchanges:
    $ref: './resources/exchanges/listCreateExchangesForAccount.yml'
  /exchanges/{id}:
    $ref: './resources/exchanges/retrieveExchangeResource.yml'
  /customers/{id}/exchanges:
    $ref: './resources/exchanges/listCreateExchangesForCustomer.yml'
  /customers/{id}/exchange-sessions:
    $ref: './resources/exchange-sessions/createCustomerExchangeSession.yml'
  /exchange-sessions/{id}:
    $ref: './resources/exchange-sessions/retrieveExchangeSession.yml'
  /exchanges/{id}/exchange-sessions:
    $ref: './resources/exchange-sessions/createReAuthExchangeSession.yml'
  /customers/{id}/available-exchange-connections:
    $ref: './resources/exchange-sessions/listAvailableExchangeConnections.yml'
  /client-tokens:
    $ref: './resources/client-tokens.yml'
components:
  securitySchemes:
    clientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: /token
          x-speakeasy-token-endpoint-authentication: client_secret_basic
          scopes: {}
security:
  - clientCredentials: []
tags:
  - name: tokens
    description: Operations related to Application Access Tokens
  - name: root
    description: Root API operations
  - name: accounts
    description: Operations related to Accounts
  - name: customers
    description: Operations related to Customers
  - name: kba
    description: Operations related to Knowledge-Based Authentication
  - name: beneficial owners
    description: Operations related to Beneficial Owners
  - name: documents
    description: Operations related to Documents
  - name: exchanges
    description: Operations related to Exchanges
  - name: exchange sessions
    description: Operations related to Exchange Sessions
  - name: funding sources
    description: Operations related to Funding Sources
  - name: transfers
    description: Operations related to Transfers
  - name: labels
    description: Operations related to Labels
  - name: mass payments
    description: Operations related to Mass Payments
  - name: events
    description: Operations related to Events
  - name: webhook subscriptions
    description: Operations related to Webhook Subscriptions
  - name: webhooks
    description: Operations related to Webhooks
  - name: client tokens
    description: Operations related to Client Tokens
