name: OpenAPI Spec Management

on:
  pull_request:
    paths:
      - 'specs/**'
      - '.github/workflows/openapi-spec.yml'

jobs:
  validate-and-bundle:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
      pull-requests: write
      statuses: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install -g @redocly/cli
          npm install -g @mintlify/cli
          curl -fsSL https://go.speakeasy.com/cli-install.sh | sh

      - name: Bundle OpenAPI spec
        run: |
          npx @redocly/cli bundle specs/spec.yml -o openapi.yml

      - name: Validate OpenAPI spec
        run: |
          npx @redocly/cli lint openapi.yml

      - name: Run Mintlify linter
        run: |
          npx mint openapi-check openapi.yml

      - name: Run Speakeasy linter
        run: |
          speakeasy lint openapi -s openapi.yml

      - name: Upload bundled spec
        uses: actions/upload-artifact@v4
        with:
          name: openapi-spec
          path: openapi.yml
          if-no-files-found: error

      - name: Check for breaking changes
        run: |
          npx @redocly/cli check-diff openapi.yml --reference origin/main
